apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "sre-playground-autoremediation"
spec:
  stages:
    - name: "sre-playground"
      sequences:
        - name: "problem-type-a-remediation"
          triggeredOn:
            - event: "sre-playground.problem-type-a.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "1m"
              properties:
                timeframe: "1m"
    - name: "problem-type-a"
      sequences:
        - name: "remediation"
          triggeredOn:
            - event: "problem-type-a.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "1m"
              properties:
                timeframe: "1m"
    - name: "problem-type-b"
      sequences:
        - name: "remediation"
          triggeredOn:
            - event: "problem-type-a.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "1m"
              properties:
                timeframe: "1m"
