apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.action.finished
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slackwebhook_token}}
          payload: >-
            payload={   "channel" : "{{.data.project}}--{{.data.service}}",  "username" : "Keptn",   "blocks": [    {      "type" : "section",      "text" : {        "type": "mrkdwn",        "text" : "*Keptn Action Finished:* [Dynatrace Problem]({{.data.labels.Problem URL}})"      }    },    {      "type" : "section",      "text" : {        "type": "mrkdwn",        "text" : "*Project:* {{.data.project}}\n*Stage:* {{.data.stage}}\n*Service:* {{.data.service}}\n*Details:* {{.env.secret_slackwebhook_bridgeUrl}}/bridge/evaluation/{{.shkeptncontext}}"      }    }  ]}
          headers: []
          method: POST
      envFrom:
        - name: secret_slackwebhook_token
          secretRef:
            name: slack-webhook
            key: token
        - name: secret_slackwebhook_bridgeUrl
          secretRef:
            name: slack-webhook
            key: bridgeUrl
      subscriptionID: 5a9365ed-6b6c-48c5-b9ac-a73609e7719f
      sendFinished: false
      sendStarted: false
